name: build-package

on:
  release:
    types: prereleased

jobs:

  build-package:
    name: Create and upload package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create zip package
      run: zip -r "cs-wordpress-blocker.zip" . -x "./tests/**" -x ".git/**" -x "./github/**"
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: cs-wordpress-blocker.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
